name: Snowflake Query Demo

on:
  push:
    branches:
      - main

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SnowSQL in Docker
        run: |
          docker run --rm -v $(pwd):/scripts \
          -e SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }} \
          -e SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }} \
          -e SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }} \
          snowflakedb/snowsql:latest \
          snowsql -a $SNOWFLAKE_ACCOUNT \
                  -u $SNOWFLAKE_USER \
                  -p $SNOWFLAKE_PASSWORD \
                  -d DEMO_DB \
                  -s PUBLIC \
                  -q "@/scripts/data.sql"
