name: Snowflake Query Demo

on:
  push:
    branches:
      - main

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/install-latest.sh
          bash install-latest.sh
          sudo ~/.snowsql/snowsql -v  # Verify installation

      - name: Run SQL Query
        run: |
          sudo ~/.snowsql/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                                  -u ${{ secrets.SNOWFLAKE_USER }} \
                                  -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                                  -d DEMO_DB \
                                  -s PUBLIC \
                                  -q "@query.sql"
