name: Snowflake Query Demo

on:
  push:
    branches:
      - main

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Run Snowflake Query with Python
        run: python run_query.py
