name: Snowflake SQL Query Demo

on:
  push:
    branches:
      - main

jobs:
  snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowSQL CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y snowsql

      - name: Run SQL query on Snowflake
        run: |
          snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                  -u ${{ secrets.SNOWFLAKE_USER }} \
                  -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                  -d DEMO_DB \
                  -s PUBLIC \
                  -q "SELECT * FROM music_catalog LIMIT 10;"
