name: Snowflake Query Demo

on:
  push:
    branches:
      - main

jobs:
  run-snowflake-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64
          chmod +x snowsql-linux_x86_64
          ./snowsql-linux_x86_64 -n

      - name: Configure SnowSQL
        run: |
          ./snowsql-linux_x86_64 -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                                 -u ${{ secrets.SNOWFLAKE_USER }} \
                                 -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                                 -d DEMO_DB \
                                 -s PUBLIC \
                                 -q "@data.sql"
